# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

steps:
- script: |
    sudo apt-get update 
    sudo apt-get install protobuf-compiler
    sudo apt-get install libboost-filesystem-dev 
    sudo apt-get install libprotobuf-dev 
    sudo apt-get install libsdl2-dev
    sudo apt-get install libboost-iostreams-dev
    make
    make clean
    RELEASE=1 make
    make clean
  displayName: 'make'
